require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'vanilla' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  target 'vanillaTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
   post_install do |installer|
       installer.pods_project.targets.each do |target|
           target.build_configurations.each do |config|
             if config.name == 'Debug'
               config.build_settings['OTHER_SWIFT_FLAGS'] = ['$(inherited)', '-Onone']
               config.build_settings['SWIFT_OPTIMIZATION_LEVEL'] = '-Owholemodule'
               config.build_settings['ENABLE_BITCODE'] = 'NO'
             end
           end
         end
        puts("Update debug pod settings to speed up build time")
        Dir.glob(File.join("Pods", "**", "Pods*{debug,Private}.xcconfig")).each do |file|
        File.open(file, 'a') { |f| f.puts "\nDEBUG_INFORMATION_FORMAT = dwarf" }
        end
      end
end

target 'vanilla-tvOS' do
  # Pods for vanilla-tvOS

  target 'vanilla-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end


